title:        agjgd
name:         agjgd
description:  agjgd is tk
author:       Andrew G. Johnson
author_email: andrew@andrewgjohnson.com
email:        andrew@andrewgjohnson.com
url:          "https://agjgd.org"
includes_dir: .
layouts_dir:  documentation/agjgd.org/layouts
exclude:      [
               CHANGELOG.md,
               CNAME,
               CODE_OF_CONDUCT.md,
               composer.json,
               CONTRIBUTING.md,
               documentation/README.md,
               ISSUE_TEMPLATE.md,
               LICENSE,
               PULL_REQUEST_TEMPLATE.md,
               README.md,
               source
              ]
