title:        agjgd.org
name:         agjgd.org
description:  agjgd is a collection of projects started by Andrew G. Johnson for PHP's GD 
author:       Andrew G. Johnson
author_email: andrew@andrewgjohnson.com
email:        agjgd.org@gmail.com
url:          "https://agjgd.org"
includes_dir: .
layouts_dir:  documentation/agjgd.org/layouts
exclude:      [
               .github,
               .github/*.md,
               .github/*.yml,
               .github/CODEOWNERS,
               CHANGELOG.md,
               CNAME,
               composer.json,
               documentation/README.md,
               examples/*.php,
               examples/*.ttf,
               LICENSE,
               README.md,
               source
              ]
