name: Generate Downloads Report

on:
  schedule:
    - cron: '0 * * * *' # run hourly
  workflow_dispatch: # allow manual triggering

permissions:
  contents: write

jobs:
  fetch-downloads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch downloads total
        run: |
          REPOS=(
            "agjgd/agjgd"
            "andrewgjohnson/imageblendedcolorallocate"
            "andrewgjohnson/imagecolorallocatefromstring"
            "andrewgjohnson/imagegradientrectangle"
            "andrewgjohnson/imagettftextblur"
            "andrewgjohnson/imagettftextgradient"
            "andrewgjohnson/linebreaks4imagettftext"
          )
          REPORT="project|downloads\n-------|----------\n"
          TOTAL_DOWNLOADS=0


          round() {
            echo $1 | awk '{printf "%d", ($1 + 0.5)}'
          }
          
          for REPO in "${REPOS[@]}"; do
            RESPONSE=$(curl -s "https://packagist.org/packages/$REPO/stats.json")
            DOWNLOADS=$(echo $RESPONSE | jq '.downloads.total')
            TOTAL_DOWNLOADS=$((TOTAL_DOWNLOADS + DOWNLOADS))
            if [ $DOWNLOADS -ge 999500 ]; then
              FORMATTED_DOWNLOADS="$(round $(echo "$DOWNLOADS / 1000000" | bc -l))M"
            elif [ $DOWNLOADS -ge 1000 ]; then
              FORMATTED_DOWNLOADS="$(round $(echo "$DOWNLOADS / 1000" | bc -l))k"
            else
              FORMATTED_DOWNLOADS=$DOWNLOADS
            fi
            USERNAME=$(echo $REPO | cut -d'/' -f1)
            REPO_NAME=$(echo $REPO | cut -d'/' -f2)
            REPORT+="[$USERNAME/**$REPO_NAME**](https://github.com/$REPO)|[$FORMATTED_DOWNLOADS](https://packagist.org/packages/$REPO/stats)\n"
          done
          if [ $TOTAL_DOWNLOADS -ge 999500 ]; then
            FORMATTED_TOTAL_DOWNLOADS="$(round $(echo "$TOTAL_DOWNLOADS / 1000000" | bc -l))M"
          elif [ $TOTAL_DOWNLOADS -ge 1000 ]; then
            FORMATTED_TOTAL_DOWNLOADS="$(round $(echo "$TOTAL_DOWNLOADS / 1000" | bc -l))k"
          else
            FORMATTED_TOTAL_DOWNLOADS=$TOTAL_DOWNLOADS
          fi          
          REPORT+="**Total downloads across all projects**|**$FORMATTED_TOTAL_DOWNLOADS**"
          echo -e "$REPORT" > DOWNLOADS.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add DOWNLOADS.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update downloads report"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
